### PR TITLE
:bug: Fix some inconsistencies

### PR DESCRIPTION
**Pull request by luxonauta**
Previously as pointed out in issue #38 , there were some inconsistencies in the themes; strings must be #F1FA8C (Yellow).

Example before this adjustment (in XML):

Screenshot before corrections

Now:

Screenshot after corrections

### CODE REVIEW

**Comment by zenorocha** [comment]
Can you retake the screenshot using these changes?

https://github.com/dracula/notepad-plus-plus/blob/master/screenshot.png

The closer you can get to the VSCode implementation, the better.

https://github.com/dracula/visual-studio-code/blob/master/screenshot.png

**Comment by zenorocha** [comment]
You can also update the Team section to include your name:
https://github.com/dracula/notepad-plus-plus/blob/master/README.md#team

**Comment by luxonauta** [comment]
> 

New example after tweaks (closer to VsCode implementation):

New Screenshot after tweaks, to get closer to VsCode

**Comment by zenorocha** [comment]
About the theme: 
1) Can we update the line numbers to be dark blue instead of white?
2-3) Is it possible to update the tokens to better match the [spec](https://spec.draculatheme.com/)?

CleanShot 2022-01-21 at 09 07 19@2x

CleanShot 2022-01-21 at 09 10 45@2x

About the screenshot: 50% of the image size is empty space. Can you retake the screenshot, increase the zoom, so the font size is bigger, and remove that empty space from it?

**Comment by luxonauta** [comment]
Unfortunately, I haven't found a way to change the colours of the line numbers to dark blue instead of white as suggested; I've verified by installing other themes that it's only possible to change the background colour. 😓

And this is the closest visual to VsCode, that I managed to get. 😅

**Comment by zenorocha** [comment]
Merged!

**Pull request merged**
