### PR TITLE
Rust syntax highlighting

### PR DESCRIPTION
**Pull request by Kazkans**
## Before
Before
## After
After

### CODE REVIEW

**Comment by ukarim** [comment]
@Kazkans 
I've just applied your changes on my machine and got following result
image
It seems because you set background color for keywords and etc. to FFFFFF.
Can you please fix this

**Comment by Kazkans** [comment]
Fixed
image

**Comment by zenorocha** [comment]
@ukarim can you take a look? It looks much better now!

**Comment by ukarim** [comment]
@Kazkans well done :thumbsup:

**Pull request merged**
